apiVersion: "monitoring.coreos.com/v1alpha1"
kind: "ServiceMonitor"
metadata:
  name: "pxc-server"
  labels:
    app: mysql-exporter
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: pxc-server
  endpoints:
  - port: "metrics"
    interval: 30s
