apiVersion: v1
kind: ConfigMap
metadata:
  name: pxc-config
data:
  root_password: my_secure_root_password
  discovery_service: etcd:2379
  cluster_name: k8scluster1
  xtrabackup_passwod: my_secure_xtrabackup_password
  mysql_proxy_user: proxyuser
  mysql_proxy_password: s3cret
  prometheus_exporter_username: exporter
  prometheus_exporter_password: s3cret2
  prometheus_exporter_data_source_name: exporter:s3cret2@(127.0.0.1:3306)/
